# -*- coding: utf-8 -*-
from portfolio_utils import run_portfolio

tickers = sorted(list(set([
    "JSWSTEEL.NS", "JINDALSTEL.NS", "JIOFIN.NS", "JUBLFOOD.NS", "KEI.NS", "KALYANKJIL.NS", "KOTAKBANK.NS", "LTF.NS", "LICHSGFIN.NS", "LTIM.NS", "LT.NS", "LICI.NS", "LODHA.NS", "LUPIN.NS", "MRF.NS", "M&MFIN.NS", "M&M.NS", "MARICO.NS", "MARUTI.NS", "MFSL.NS", "MAXHEALTH.NS", "MAZDOCK.NS", "MOTILALOFS.NS", "MPHASIS.NS", "MUTHOOTFIN.NS", "NHPC.NS", "NMDC.NS", "NTPCGREEN.NS", "NTPC.NS", "NATIONALUM.NS", "NESTLEIND.NS", "OBEROIRLTY.NS", "OIL.NS", "PAYTM.NS" , "OFSS.NS", "PIIND.NS", "PAGEIND.NS", "PATANJALI.NS", "PERSISTENT.NS", "PHOENIXLTD.NS", "PIDILITIND.NS", "POLYCAB.NS", "PFC.NS", "POWERGRID.NS", "PREMIERENE.NS", "PRESTIGE.NS", "PNB.NS", "RECLTD.NS", "RELIANCE.NS", "SBICARD.NS", "SBILIFE.NS", "SRF.NS", "MOTHERSON.NS", "SHREECEM.NS", "SHRIRAMFIN.NS", "ENRIN.NS", "SIEMENS.NS", "SOLARINDS.NS", "SONACOMS.NS", "SAIL.NS", "SUNPHARMA.NS", "SUPREMEIND.NS", "SUZLON.NS", "TVSMOTOR.NS", "TATACOMM.NS", "TATACONSUM.NS", "TATAELXSI.NS", "TATAMOTORS.NS", "TATAPOWER.NS", "TATASTEEL.NS", "TATATECH.NS", "TECHM.NS", "TITAN.NS", "TORNTPHARM.NS", "TORNTPOWER.NS", "TRENT.NS", "TIINDIA.NS", "UPL.NS", "ULTRACEMCO.NS", "UNIONBANK.NS", "UNITDSPR.NS", "VBL.NS", "VEDL.NS", "VMM.NS", "IDEA.NS", "VOLTAS.NS", "WAAREEENER.NS", "WIPRO.NS", "YESBANK.NS", "ZYDUSLIFE.NS"
])))

if __name__ == "__main__":
    run_portfolio(tickers, "5_days_history_pan2.csv", "pan2_2year_history.csv")
